
application: daniellawrencelu
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1d"
handlers:

# old urls
- url: /s/.*
  script: main.app

# blog
- url: /blog/
  script: main.app

# not index files
- url: /(.*\.((png)|(jpg)|(svg)))
  static_files: static/\1
  upload: static/(.*\.(png)|(jpg)|(svg))
  expiration: "30d"

# not index files
- url: /(.*\..+)
  static_files: static/\1
  upload: static/(.*\..+)
  expiration: "1d"

# index files
- url: (.*)/
  static_files: static\1/index.html
  upload: static(.*)/index.html
  expiration: "1d"

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest